<?php

namespace EmailScheduler\Command;

use Composer\Script\Event;

class Install {
	
	/**
	 * Install the parameters file
	 * 
	 * @param Event $event The Composer Script Event
	 */
	public static function parameters(Event $event)	{
		
		$defaultParams = parse_ini_file(__DIR__ . '/../Resources/config/parameters.ini.dist', true);
		
		$io = $event->getIO();
		
		$io->write('Email Scheduler Parameter Configuration...');
		
		$file = __DIR__ . '/../Resources/config/parameters.php';
		
		if (file_exists($file)) {
			if (!in_array(strtolower($io->ask('It looks like parameters.php already exists, do you want to continue? [yes|no]: ', 'yes')), array('y','yes'))) {
				$io->write('Execution Halted.');
				return;
			}
		}
		
		$paramStr = array(
			'<?php ' ,
			'',
			'// You should not edit this file' ,
			'// This file is automatically generated from parameters.ini.dist' ,
			'' ,
		);
		
		$count = 0;
		$str = "return array(";
		foreach ($defaultParams as $section => $data) {

			if (++$count > 1) {
				$str .= ",";
			}
			
			$str .= "\n\t" . '"' . $section . '" => array(';

			$subCount = 0;
			foreach ($data as $key => $value) {

				if (++$subCount > 1) {
					$str .= ",";
				}
				
				$str .= "\n\t\t" . '"' . $key . '" => "' . $io->ask($section . '.' . $key . ($value ? ' [' . $value . ']: ' : ': '), $value ?: null) . '"';
			}
			
			$str .= "\n\t)";
		}
		$str .= "\n);\n";
		
		$paramStr[] = $str;
		
		file_put_contents($file, join("\n", $paramStr));
	}
}
